### ISSUE TITLE
handle query params

### ISSUE THREAD

**Issue by bigjust** [narfman0/helga-youtube-metadata#1]
for instance, if https://www.youtube.com/watch?time_continue=7&v=Y-Elr5K2Vuo   is given, because i accidently watched 7s and used the auto copy link which includes the timestamp, the regex fails

**Comment by narfman0** [comment]
Good catch! I think I fixed in 1.0.13, try it out. I spammed some boilerplate testing stuff too for "next time"

**Comment by bigjust** [comment]
Works, thanks!

**Comment by narfman0** [comment]
1.1.0 supports this as a setting also! :)
